### ISSUE TITLE
ResourceQuota utilization computed incorrectly

### ISSUE THREAD

**Issue by tohjustin** [aptakube/aptakube#465]
### Current and expected behavior

Doesn't seem like AptaKube properly accounts for quantity suffixes when computing quota utilization.

<img width="1113" height="245" alt="Image" src="https://github.com/user-attachments/assets/66a1788f-b281-4017-b49c-73adf81c90f6" />

```
apiVersion: v1
kind: ResourceQuota
metadata:
  creationTimestamp: 2025-06-09T07:34:27Z
  name: gitops-auto-detect-edge-not-best-effort-quota
  namespace: gitops-auto-detect-edge
  resourceVersion: "2887148024"
  uid: cfd5681d-b767-4e74-a464-7a2e02a5081a
spec:
  hard:
    limits.cpu: 3k
    limits.memory: 1Gi
    requests.bge-physical-b16/cpu-limit: 3k
    requests.bge-physical-b16/cpu-request: 1k
    requests.bge-physical-b16/memory: 1Gi
    requests.bge-physical-z04/cpu-limit: "0"
    requests.bge-physical-z04/cpu-request: "0"
    requests.bge-physical-z04/memory: "0"
    requests.cpu: 1k
    requests.memory: 1Gi
  scopes:
    - NotBestEffort
status:
  hard:
    limits.cpu: 3k
    limits.memory: 1Gi
    requests.bge-physical-b16/cpu-limit: 3k
    requests.bge-physical-b16/cpu-request: 1k
    requests.bge-physical-b16/memory: 1Gi
    requests.bge-physical-z04/cpu-limit: "0"
    requests.bge-physical-z04/cpu-request: "0"
    requests.bge-physical-z04/memory: "0"
    requests.cpu: 1k
    requests.memory: 1Gi
  used:
    limits.cpu: "1"
    limits.memory: 128Mi
    requests.bge-physical-b16/cpu-limit: 1k
    requests.bge-physical-b16/cpu-request: "100"
    requests.bge-physical-b16/memory: 128Mi
    requests.bge-physical-z04/cpu-limit: "0"
    requests.bge-physical-z04/cpu-request: "0"
    requests.bge-physical-z04/memory: "0"
    requests.cpu: 100m
    requests.memory: 128Mi
```

### Environment & Operating System

- macOS Sequoia 15.1.1 (24B91)
- Kubernetes v1.21.14

**Comment by goenning** [comment]
Oh, I didn't know you could be specific like that with the requests. Will fix it on the next patch 👍

**Comment by goenning** [comment]
Fixed on 1.12.3

**Comment by tohjustin** [comment]
Hi @goenning, thanks for the quick turnaround!

### Current and expected behavior

I've upgraded `v1.12.4` which contains the fixed, but I think there are still some edge cases not handled yet 😅

I'm still seeing the bug in the quotas of our extended resources (eg. `requests.bge-physical-b16-rtc/memory`).

---

<img width="603" height="243" alt="Image" src="https://github.com/user-attachments/assets/c5c9717c-6abd-402c-982b-e7f1f466f721" />

```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gitops-platform-logs-not-best-effort-quota
  namespace: gitops-platform-logs
spec:
  hard:
    limits.cpu: 2820k
    limits.memory: 2430Gi
    requests.bge-physical-b16-rtc/cpu-limit: 660k
    requests.bge-physical-b16-rtc/cpu-request: 220k
    requests.bge-physical-b16-rtc/memory: 430Gi
    requests.bge-physical-b16/cpu-limit: 510k
    requests.bge-physical-b16/cpu-request: 170k
    requests.bge-physical-b16/memory: 500Gi
    requests.bge-physical-s19/cpu-limit: 1650k
    requests.bge-physical-s19/cpu-request: 550k
    requests.bge-physical-s19/memory: 1500Gi
    requests.cpu: 940k
    requests.memory: 2430Gi
  scopes:
    - NotBestEffort
status:
  hard:
    limits.cpu: 2820k
    limits.memory: 2430Gi
    requests.bge-physical-b16-rtc/cpu-limit: 660k
    requests.bge-physical-b16-rtc/cpu-request: 220k
    requests.bge-physical-b16-rtc/memory: 430Gi
    requests.bge-physical-b16/cpu-limit: 510k
    requests.bge-physical-b16/cpu-request: 170k
    requests.bge-physical-b16/memory: 500Gi
    requests.bge-physical-s19/cpu-limit: 1650k
    requests.bge-physical-s19/cpu-request: 550k
    requests.bge-physical-s19/memory: 1500Gi
    requests.cpu: 940k
    requests.memory: 2430Gi
  used:
    limits.cpu: 1782100m
    limits.memory: 2271Gi
    requests.bge-physical-b16-rtc/cpu-limit: "342500"
    requests.bge-physical-b16-rtc/cpu-request: "183500"
    requests.bge-physical-b16-rtc/memory: 391808Mi
    requests.bge-physical-b16/cpu-limit: 338k
    requests.bge-physical-b16/cpu-request: 143k
    requests.bge-physical-b16/memory: 455936Mi
    requests.bge-physical-s19/cpu-limit: "1101600"
    requests.bge-physical-s19/cpu-request: "492310"
    requests.bge-physical-s19/memory: 1477760Mi
    requests.cpu: 818810m
    requests.memory: 1893056Mi
```

<img width="601" height="244" alt="Image" src="https://github.com/user-attachments/assets/dd4255bc-1fa2-4942-8e4a-ca29fe7ee40b" />

```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gitops-platform-metrics-not-best-effort-quota
  namespace: gitops-platform-metrics
spec:
  hard:
    limits.cpu: 630k
    limits.memory: 1390Gi
    requests.bge-physical-b16-rtc/cpu-limit: 150k
    requests.bge-physical-b16-rtc/cpu-request: 50k
    requests.bge-physical-b16-rtc/memory: 350Gi
    requests.bge-physical-b16/cpu-limit: 180k
    requests.bge-physical-b16/cpu-request: 60k
    requests.bge-physical-b16/memory: 440Gi
    requests.bge-physical-s19/cpu-limit: 300k
    requests.bge-physical-s19/cpu-request: 100k
    requests.bge-physical-s19/memory: 600Gi
    requests.cpu: 210k
    requests.memory: 1390Gi
  scopes:
    - NotBestEffort
status:
  hard:
    limits.cpu: 630k
    limits.memory: 1390Gi
    requests.bge-physical-b16-rtc/cpu-limit: 150k
    requests.bge-physical-b16-rtc/cpu-request: 50k
    requests.bge-physical-b16-rtc/memory: 350Gi
    requests.bge-physical-b16/cpu-limit: 180k
    requests.bge-physical-b16/cpu-request: 60k
    requests.bge-physical-b16/memory: 440Gi
    requests.bge-physical-s19/cpu-limit: 300k
    requests.bge-physical-s19/cpu-request: 100k
    requests.bge-physical-s19/memory: 600Gi
    requests.cpu: 210k
    requests.memory: 1390Gi
  used:
    limits.cpu: 373170m
    limits.memory: "716630051328"
    requests.bge-physical-b16-rtc/cpu-limit: "103200"
    requests.bge-physical-b16-rtc/cpu-request: "21600"
    requests.bge-physical-b16-rtc/memory: 156000Mi
    requests.bge-physical-b16/cpu-limit: "77940"
    requests.bge-physical-b16/cpu-request: "41450"
    requests.bge-physical-b16/memory: 238142Mi
    requests.bge-physical-s19/cpu-limit: "192030"
    requests.bge-physical-s19/cpu-request: "41005"
    requests.bge-physical-s19/memory: "303342209536"
    requests.cpu: 104055m
    requests.memory: "712431553024"
```

### Environment & Operating System

- macOS Sequoia 15.1.1 (24B91)
- Kubernetes v1.21.14

**Comment by goenning** [comment]
Oops, I missed those! Can you try this beta?

https://releases.aptakube.com/Aptakube_1.12.5-beta1_universal.dmg

**Comment by goenning** [comment]
Wait, I think there's still an issue.

I thought that `cpu: 1k` === `cpu: 1000`, but it seems like `cpu: 1k` === `cpu: 1` === `cpu: 1000m`

**Comment by goenning** [comment]
Ok, I may have fixed it on https://releases.aptakube.com/Aptakube_1.12.5-beta2_universal.dmg

Let me know how it goes! :)

**Comment by tohjustin** [comment]
> Wait, I think there's still an issue.
> 
> I thought that `cpu: 1k` === `cpu: 1000`, but it seems like `cpu: 1k` === `cpu: 1` === `cpu: 1000m`

@goenning Apologies I forgot to mention, there's actually an ongoing bug on our extended resources implementation (we have an abstraction layer over our node's CPU resources based on bare metal server type). 😰
> Context: Our intended design for extended CPU resource to being tracked in millicores, so we want `requests.bge-physical-b16/cpu-limit: "77940"` to mean `77940` millicores or `77.94` cores (equivalent to `limits.cpu: "77.94"`).

The bug we have right now is that the hard CPU requests/limits in our ResourceQuotas are set incorrectly (off by factor of 1000, for example the `limits.cpu: 630k` that you see should be `limits.cpu: 630` instead) so that makes it confusing when you look at the ResourceQuota values that I've shared...

Maybe we should just parse the values according to https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes & https://kubernetes.io/docs/reference/kubernetes-api/common-definitions/quantity/ 🤔

**Comment by tohjustin** [comment]
The bug that I was referring to in https://github.com/aptakube/aptakube/issues/465#issuecomment-3142031639 back in 1st Aug were that the memory utilization values showed were over 1000% (the CPU utilizations are actually computed correctly 🥲)
<img width="601" height="244" alt="Image" src="https://github.com/user-attachments/assets/0226d9a5-9432-4364-8d0c-3e3ff4b4ccd4" />
```
requests.bge-physical-b16-rtc/memory --> 156000Mi / 350Gi = 156000Mi / 358400Mi = 0.4352678571 = 43%
requests.bge-physical-b16/memory --> 238142Mi / 440Gi = 238142Mi / 450560Mi = 0.5285466974 = 53%
requests.bge-physical-s19/memory --> 303342209536 / 600Gi = 303342209536 / 644245094400 = 0.4708490793 = 47%
```

**Comment by goenning** [comment]
Have you tried it on 1.12.5?

**Comment by tohjustin** [comment]
@goenning Yup, I've tested `v1.12.5-beta2`.
- The memory utilization now looks correct 
- But the CPU hard & used values are incorrect, I don't think Aptakube needs to divide by 1000.

> **v1.12.4**
> <img width="946" height="227" alt="Image" src="https://github.com/user-attachments/assets/297091d9-dda3-4c7f-9f33-eaeefb2ea395" />
> **v1.12.5-beta2**
> <img width="953" height="244" alt="Image" src="https://github.com/user-attachments/assets/5fbf0c9e-942f-48d6-9820-53d4dbe10a5b" />
---

ResourceQuota for reference
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gitops-platform-metrics-not-best-effort-quota
  namespace: gitops-platform-metrics
spec:
  hard:
    limits.cpu: 630k
    limits.memory: 1390Gi
    requests.bge-physical-b16-rtc/cpu-limit: 150k
    requests.bge-physical-b16-rtc/cpu-request: 50k
    requests.bge-physical-b16-rtc/memory: 350Gi
    requests.bge-physical-b16/cpu-limit: 180k
    requests.bge-physical-b16/cpu-request: 60k
    requests.bge-physical-b16/memory: 440Gi
    requests.bge-physical-s19/cpu-limit: 300k
    requests.bge-physical-s19/cpu-request: 100k
    requests.bge-physical-s19/memory: 600Gi
    requests.cpu: 210k
    requests.memory: 1390Gi
  scopes:
    - NotBestEffort
status:
  hard:
    limits.cpu: 630k
    limits.memory: 1390Gi
    requests.bge-physical-b16-rtc/cpu-limit: 150k
    requests.bge-physical-b16-rtc/cpu-request: 50k
    requests.bge-physical-b16-rtc/memory: 350Gi
    requests.bge-physical-b16/cpu-limit: 180k
    requests.bge-physical-b16/cpu-request: 60k
    requests.bge-physical-b16/memory: 440Gi
    requests.bge-physical-s19/cpu-limit: 300k
    requests.bge-physical-s19/cpu-request: 100k
    requests.bge-physical-s19/memory: 600Gi
    requests.cpu: 210k
    requests.memory: 1390Gi
  used:
    limits.cpu: 373170m
    limits.memory: "716630051328"
    requests.bge-physical-b16-rtc/cpu-limit: "103200"
    requests.bge-physical-b16-rtc/cpu-request: "21600"
    requests.bge-physical-b16-rtc/memory: 156000Mi
    requests.bge-physical-b16/cpu-limit: "77940"
    requests.bge-physical-b16/cpu-request: "41450"
    requests.bge-physical-b16/memory: 238142Mi
    requests.bge-physical-s19/cpu-limit: "192030"
    requests.bge-physical-s19/cpu-request: "41005"
    requests.bge-physical-s19/memory: "303342209536"
    requests.cpu: 104055m
    requests.memory: "712431553024"
```

**Comment by goenning** [comment]
But it's this caused by the bug you mentioned above?

If we parse it as described on k8s documentation, "21600" is larger than "50k".

**Comment by tohjustin** [comment]
> But it's this caused by the bug you mentioned above?

Our internal bug is that when we set CPU requests/limits quotas on our internal portal, it gets translated to an incorrect value in our ResourceQuota resource.

eg. When we configure CPU request of `10 cores` & limit of `30 cores` on s19 servers in our internal portal, the bug causes our platform to update the ResourceQuota to set CPU request & limit of `10000 cores` & `30000 cores` respectively.
> ```yaml
> apiVersion: v1
> kind: ResourceQuota
> metadata:
>   name: example-quota
>   namespace: example
> spec:
>   hard:
>     requests.cpu: 10k
>     limits.cpu: 30k
>     requests.bge-physical-s19/cpu-request: 10k
>     requests.bge-physical-s19/cpu-limit: 30k
> ```

This is the correct ResourceQuota that we expect to get if our internal bug were to be fixed.
> ```yaml
> apiVersion: v1
> kind: ResourceQuota
> metadata:
>   name: example-quota
>   namespace: example
> spec:
>   hard:
>     requests.cpu: 10
>     limits.cpu: 30
>     # By design, we intentionally track our extended CPU resources
>     # (eg. `requests.bge-physical-XXX/cpu-request`) in millicores
>     requests.bge-physical-s19/cpu-request: 10k
>     requests.bge-physical-s19/cpu-limit: 30k
> ```

**Comment by tohjustin** [comment]
> If we parse it as described on k8s documentation, "21600" is larger than "50k".
> https://github.com/aptakube/aptakube/issues/465#issuecomment-3153521123

According to the documentation (https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#resource-units-in-kubernetes), don't we just perform SI prefix conversion?

i.e. `50k` equivalent to `50000`, so "21600" is ~~larger~~ smaller than "50k"?

**Comment by goenning** [comment]
> i.e. 50k equivalent to 50000, so "21600" is larger smaller than "50k"?

I believe you're missing the "m" suffix on that 21600, because:

50k = 50 CPU
50000 = 50000 CPU
50000m = 50 CPU
21600 = 21600 CPU
21600m = 21.6 CPU

Can you confirm?

**Comment by tohjustin** [comment]
Should it be this instead?
> 50k = ~50 CPU~ 50000 CPU
> 50000 = 50000 CPU
> 50000m = 50 CPU
> 21600 = 21600 CPU
> 21600m = 21.6 CPU

**Comment by goenning** [comment]
Damn it, this is confusing, but you're right! Sorry about all the back and forth.

Want to try this one? It should be correct now (I hope 🤞)

https://releases.aptakube.com/Aptakube_1.12.6-beta1_universal.dmg

**Comment by tohjustin** [comment]
No worries, appreciate you for diving into this issue.

Looks good on my end now 🙏
> v1.12.6-beta1
> <img width="875" height="208" alt="Image" src="https://github.com/user-attachments/assets/9645bccd-d0ad-4252-9e0a-627c92914f95" />
> <img width="903" height="497" alt="Image" src="https://github.com/user-attachments/assets/0e1b860d-0041-4cc9-8870-a0b6d4831a49" />
```yaml
apiVersion: v1
kind: ResourceQuota
metadata:
  name: gitops-platform-metrics-not-best-effort-quota
  namespace: gitops-platform-metrics
spec:
  hard:
    limits.cpu: 630k
    limits.memory: 1390Gi
    requests.bge-physical-b16-rtc/cpu-limit: 150k
    requests.bge-physical-b16-rtc/cpu-request: 50k
    requests.bge-physical-b16-rtc/memory: 350Gi
    requests.bge-physical-b16/cpu-limit: 180k
    requests.bge-physical-b16/cpu-request: 60k
    requests.bge-physical-b16/memory: 440Gi
    requests.bge-physical-s19/cpu-limit: 300k
    requests.bge-physical-s19/cpu-request: 100k
    requests.bge-physical-s19/memory: 600Gi
    requests.cpu: 210k
    requests.memory: 1390Gi
  scopes:
    - NotBestEffort
status:
  hard:
    limits.cpu: 630k
    limits.memory: 1390Gi
    requests.bge-physical-b16-rtc/cpu-limit: 150k
    requests.bge-physical-b16-rtc/cpu-request: 50k
    requests.bge-physical-b16-rtc/memory: 350Gi
    requests.bge-physical-b16/cpu-limit: 180k
    requests.bge-physical-b16/cpu-request: 60k
    requests.bge-physical-b16/memory: 440Gi
    requests.bge-physical-s19/cpu-limit: 300k
    requests.bge-physical-s19/cpu-request: 100k
    requests.bge-physical-s19/memory: 600Gi
    requests.cpu: 210k
    requests.memory: 1390Gi
  used:
    limits.cpu: 373170m
    limits.memory: "716630051328"
    requests.bge-physical-b16-rtc/cpu-limit: "103200"
    requests.bge-physical-b16-rtc/cpu-request: "21600"
    requests.bge-physical-b16-rtc/memory: 156000Mi
    requests.bge-physical-b16/cpu-limit: "77940"
    requests.bge-physical-b16/cpu-request: "41450"
    requests.bge-physical-b16/memory: 238142Mi
    requests.bge-physical-s19/cpu-limit: "192030"
    requests.bge-physical-s19/cpu-request: "41005"
    requests.bge-physical-s19/memory: "303342209536"
    requests.cpu: 104055m
    requests.memory: "712431553024"
```

**Comment by tohjustin** [comment]
Hi @goenning, I've upgraded to Aptakube `v1.12.6` & can confirmed that the issue has been resolved.
Thanks for fixing this! 🙏
